/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConversationRequest,
  ConversationResponse,
  MessageRequest,
  MessageResponse,
} from '../models/index';
import {
    ConversationRequestFromJSON,
    ConversationRequestToJSON,
    ConversationResponseFromJSON,
    ConversationResponseToJSON,
    MessageRequestFromJSON,
    MessageRequestToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
} from '../models/index';

export interface CreateRequest {
    conversationRequest: ConversationRequest;
}

export interface CreateMessageRequest {
    conversationId: number;
    messageRequest: MessageRequest;
}

export interface FindMessagesByConversationIdRequest {
    conversationId: number;
}

/**
 * 
 */
export class ConversationControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for create without sending the request
     */
    async createRequestOpts(requestParameters: CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationRequest'] == null) {
            throw new runtime.RequiredError(
                'conversationRequest',
                'Required parameter "conversationRequest" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/conversations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConversationRequestToJSON(requestParameters['conversationRequest']),
        };
    }

    /**
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationResponse>> {
        const requestOptions = await this.createRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationResponseFromJSON(jsonValue));
    }

    /**
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createMessage without sending the request
     */
    async createMessageRequestOpts(requestParameters: CreateMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling createMessage().'
            );
        }

        if (requestParameters['messageRequest'] == null) {
            throw new runtime.RequiredError(
                'messageRequest',
                'Required parameter "messageRequest" was null or undefined when calling createMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/conversations/{conversationId}/messages`;
        urlPath = urlPath.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessageRequestToJSON(requestParameters['messageRequest']),
        };
    }

    /**
     */
    async createMessageRaw(requestParameters: CreateMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const requestOptions = await this.createMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async createMessage(requestParameters: CreateMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.createMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for findForConnectedUser without sending the request
     */
    async findForConnectedUserRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/conversations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async findForConnectedUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ConversationResponse>>> {
        const requestOptions = await this.findForConnectedUserRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConversationResponseFromJSON));
    }

    /**
     */
    async findForConnectedUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConversationResponse>> {
        const response = await this.findForConnectedUserRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for findMessagesByConversationId without sending the request
     */
    async findMessagesByConversationIdRequestOpts(requestParameters: FindMessagesByConversationIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling findMessagesByConversationId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/conversations/{conversationId}/messages`;
        urlPath = urlPath.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async findMessagesByConversationIdRaw(requestParameters: FindMessagesByConversationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MessageResponse>>> {
        const requestOptions = await this.findMessagesByConversationIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MessageResponseFromJSON));
    }

    /**
     */
    async findMessagesByConversationId(requestParameters: FindMessagesByConversationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MessageResponse>> {
        const response = await this.findMessagesByConversationIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
