/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface ConversationResponse
 */
export interface ConversationResponse {
    /**
     * 
     * @type {number}
     * @memberof ConversationResponse
     */
    id?: number;
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof ConversationResponse
     */
    participants?: Array<UserResponse>;
}

/**
 * Check if a given object implements the ConversationResponse interface.
 */
export function instanceOfConversationResponse(value: object): value is ConversationResponse {
    return true;
}

export function ConversationResponseFromJSON(json: any): ConversationResponse {
    return ConversationResponseFromJSONTyped(json, false);
}

export function ConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'participants': json['participants'] == null ? undefined : ((json['participants'] as Array<any>).map(UserResponseFromJSON)),
    };
}

export function ConversationResponseToJSON(json: any): ConversationResponse {
    return ConversationResponseToJSONTyped(json, false);
}

export function ConversationResponseToJSONTyped(value?: ConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'participants': value['participants'] == null ? undefined : ((value['participants'] as Array<any>).map(UserResponseToJSON)),
    };
}

