/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationRequest
 */
export interface ConversationRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConversationRequest
     */
    participantUids?: Array<string>;
}

/**
 * Check if a given object implements the ConversationRequest interface.
 */
export function instanceOfConversationRequest(value: object): value is ConversationRequest {
    return true;
}

export function ConversationRequestFromJSON(json: any): ConversationRequest {
    return ConversationRequestFromJSONTyped(json, false);
}

export function ConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'participantUids': json['participantUids'] == null ? undefined : json['participantUids'],
    };
}

export function ConversationRequestToJSON(json: any): ConversationRequest {
    return ConversationRequestToJSONTyped(json, false);
}

export function ConversationRequestToJSONTyped(value?: ConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participantUids': value['participantUids'],
    };
}

