/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageRequest
 */
export interface MessageRequest {
    /**
     * 
     * @type {string}
     * @memberof MessageRequest
     */
    text?: string;
}

/**
 * Check if a given object implements the MessageRequest interface.
 */
export function instanceOfMessageRequest(value: object): value is MessageRequest {
    return true;
}

export function MessageRequestFromJSON(json: any): MessageRequest {
    return MessageRequestFromJSONTyped(json, false);
}

export function MessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function MessageRequestToJSON(json: any): MessageRequest {
    return MessageRequestToJSONTyped(json, false);
}

export function MessageRequestToJSONTyped(value?: MessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

