/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';
import type { ConversationResponse } from './ConversationResponse';
import {
    ConversationResponseFromJSON,
    ConversationResponseFromJSONTyped,
    ConversationResponseToJSON,
    ConversationResponseToJSONTyped,
} from './ConversationResponse';

/**
 * 
 * @export
 * @interface MessageResponse
 */
export interface MessageResponse {
    /**
     * 
     * @type {number}
     * @memberof MessageResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageResponse
     */
    text?: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof MessageResponse
     */
    user?: UserResponse;
    /**
     * 
     * @type {ConversationResponse}
     * @memberof MessageResponse
     */
    conversation?: ConversationResponse;
}

/**
 * Check if a given object implements the MessageResponse interface.
 */
export function instanceOfMessageResponse(value: object): value is MessageResponse {
    return true;
}

export function MessageResponseFromJSON(json: any): MessageResponse {
    return MessageResponseFromJSONTyped(json, false);
}

export function MessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'user': json['user'] == null ? undefined : UserResponseFromJSON(json['user']),
        'conversation': json['conversation'] == null ? undefined : ConversationResponseFromJSON(json['conversation']),
    };
}

export function MessageResponseToJSON(json: any): MessageResponse {
    return MessageResponseToJSONTyped(json, false);
}

export function MessageResponseToJSONTyped(value?: MessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'user': UserResponseToJSON(value['user']),
        'conversation': ConversationResponseToJSON(value['conversation']),
    };
}

